In [3]:
import numpy as np

In [4]:
A=np.array([1,2,3,4])

In [5]:
print(A)

[1 2 3 4]


In [6]:
np.ndim(A)

1

In [7]:
A.shape

(4,)

In [8]:
A.shape[0]

4

In [9]:
B=np.array([[1,2],[3,4],[5,6]])

In [10]:
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
np.ndim(B)

2

In [12]:
B.shape

(3, 2)

In [17]:
A=np.array([[1,2,3],[4,5,6]])
A.shape
B=np.array([[1,2],[3,4],[5,6]])

In [18]:
B.shape

(3, 2)

In [19]:
np.dot(A,B)

array([[22, 28],
       [49, 64]])